### ISSUE TITLE
Log format issue with Python 3

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [spreaker/prometheus-pgbouncer-exporter#30]
Im getting the below error in Python 3. (`Python 3.8.2`)

### Error:

```py
pgbouncer-exporter --config ./config.yml
Traceback (most recent call last):
  File "/usr/local/bin/pgbouncer-exporter", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/prometheus_pgbouncer_exporter/cli.py", line 47, in main
    formatter = jsonlogger.JsonFormatter("(asctime) (levelname) (message)", datefmt="%Y-%m-%d %H:%M:%S")
  File "/usr/local/lib/python3.8/dist-packages/pythonjsonlogger/jsonlogger.py", line 112, in __init__
    logging.Formatter.__init__(self, *args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 576, in __init__
    self._style.validate()
  File "/usr/lib/python3.8/logging/__init__.py", line 429, in validate
    raise ValueError("Invalid format '%s' for '%s' style" % (self._fmt, self.default_format[0]))
ValueError: Invalid format '(asctime) (levelname) (message)' for '%' style
```

**Comment by BhuviTheDataGuy** [comment]
Im able to solve this by replacing the following line from the file `prometheus_pgbouncer_exporter/cli.py`
Line number 47
```py
formatter = jsonlogger.JsonFormatter("%(message)%(levelname)%(name)%(asctime)")
```

**Comment by alexandrenegreira** [comment]
I have encountered the same problem in Python 3.8.5 and I have solved it in the same way as you expose.

**Comment by BhuviTheDataGuy** [comment]
Glad it worked.

**Comment by Ferroman** [comment]
It would be very helpful if someone could take some time to review the fix https://github.com/spreaker/prometheus-pgbouncer-exporter/pull/33 It would be great to have it in mainline.

**Comment by asomers** [comment]
@spreaker can we please reopen this bug?  The issue is still present in master, and Ferroman's PR fixes it.
